# -*- coding: utf-8 -*-
"""DST Team Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MG86bzywSB12pJZoQnOap1LJ0rygZD0C

# **Made by : اشغال حاسبات جدا**

# **1. Data Extraction Using BeautifulSoup**
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import re
import seaborn as sns

# الموقع الأساسي
base_url = "https://books.toscrape.com/catalogue/"
start_url = "https://books.toscrape.com/catalogue/page-1.html"

books = []

# هنلف على كل الصفحات
while start_url:
    response = requests.get(start_url)
    soup = BeautifulSoup(response.text, "html.parser")

    # كل الكتب في الصفحة
    books_list = soup.select(".product_pod")

    for book in books_list:
        title = book.h3.a["title"]
        book_url = base_url + book.h3.a["href"].replace('../../../', '')

        # ندخل على صفحة كل كتاب عشان نجيب التفاصيل
        book_response = requests.get(book_url)
        book_soup = BeautifulSoup(book_response.text, "html.parser")

        # النوع
        genre = book_soup.select("ul.breadcrumb li:nth-of-type(3) a")[0].text.strip()

        # السعر شامل الضريبة
        price = book_soup.select("table tr:contains('Price (incl. tax)') td")[0].text.strip()

        # التقييم (بالكلمة، فهنحوّله لرقم)
        rating_class = book.select_one("p.star-rating")["class"][1]
        rating_dict = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
        rating = rating_dict.get(rating_class, 0)

        # الحالة (Available ولا لأ)
        availability = book_soup.select("table tr:contains('Availability') td")[0].text.strip()

        books.append({
            "Title": title,
            "Genre": genre,
            "Price (incl. tax)": price,
            "Rating": rating,
            "Availability": availability
        })

    # الصفحة الجاية
    next_btn = soup.select_one("li.next a")
    if next_btn:
        next_href = next_btn["href"]
        start_url = "https://books.toscrape.com/catalogue/" + next_href
    else:
        start_url = None


df = pd.DataFrame(books)

# نحفظ الداتا في CSV
df = pd.DataFrame(books)
df.to_csv("books_data.csv", index=False)

print("Done! البيانات اتحفظت في books_data.csv")

df.info()
print(df)

"""# **2. Data Cleaning & Regex**"""

# تنظيف السعر
def clean_price(raw_price):
    raw_price = str(raw_price).strip()
    raw_price = raw_price.replace("£", "").replace("\u200b", "").strip()
    match = re.search(r"\d+\.\d+|\d+", raw_price)
    if match:
        return float(match.group())
    else:
        return 0.0

df["Price (incl. tax)"] = df["Price (incl. tax)"].apply(clean_price)

# تنظيف التوفر
df["Availability"] = df["Availability"].apply(
    lambda x: int(re.search(r"\d+", str(x)).group())
    if re.search(r"\d+", str(x))
     else 0
)

# تنظيف العنوان
df["Title"] = df["Title"].apply(
    lambda x: re.sub(r"[^\w\s\-&]", "", str(x)).strip()
)

df.info()
print(df)

# حساب حدود IQR
Q1 = df["Price (incl. tax)"].quantile(0.25)
Q3 = df["Price (incl. tax)"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# استخراج القيم الشاذة
outliers = df[(df["Price (incl. tax)"] < lower_bound) | (df["Price (incl. tax)"] > upper_bound)]

# عرض عدد القيم الشاذة
print(f"عدد القيم الشاذة: {len(outliers)}")
print(outliers[["Title", "Price (incl. tax)"]])

df.describe()

# رسم Boxplot
plt.figure(figsize=(8, 5))
plt.boxplot(df["Price (incl. tax)"], vert=False)
plt.title("Boxplot of Book Prices (incl. tax)")
plt.xlabel("Price")
plt.grid(True)
plt.show()

"""# **3-4. Data Analysis and data visualization**

**1. Average Price per Genre**

We calculated the average price of books across different genres.
Observation: Some genres, like Suspense and Politics, tend to have higher average prices compared to others like Crime and Academic.
"""

avg_price_genre = df.groupby('Genre')["Price (incl. tax)"].mean().sort_values(ascending=False)

plt.figure(figsize=(12,6))
sns.barplot(x=avg_price_genre.values, y=avg_price_genre.index, palette="viridis")
plt.title("Average Price per Genre")
plt.xlabel("Average Price (£)")
plt.ylabel("Genre")
plt.tight_layout()
plt.show()

""" **2. Average Rating per Genre**
We computed the average book rating for each genre.
Observation: Certain genres show consistently higher ratings, suggesting better reception or quality among readers like: Erotica, Adult fiction, Novels.
"""

avg_rating_genre = df.groupby('Genre')["Rating"].mean().sort_values(ascending=False)

plt.figure(figsize=(12,6))
sns.barplot(x=avg_rating_genre.values, y=avg_rating_genre.index, palette="coolwarm")
plt.title("Average Rating per Genre")
plt.xlabel("Average Rating")
plt.ylabel("Genre")
plt.tight_layout()
plt.show()

""" **3. Price Distribution**
We analyzed the overall distribution of book prices.
Observation: Most books are priced between £20 and £50, with a few priced higher.
"""

plt.figure(figsize=(10,6))
sns.histplot(df["Price (incl. tax)"], kde=True, color="blue", bins=30)
plt.title("Price Distribution of Books")
plt.xlabel("Price (£)")
plt.ylabel("Number of Books")
plt.tight_layout()
plt.show()

""" **4. Rating Distribution**
We examined the spread of book ratings.
Observation: The analysis of book ratings reveals a relatively even distribution across the 1-to-5 scale, with each rating category receiving a significant share.
"""

rating_counts = df["Rating"].value_counts().sort_index()

plt.figure(figsize=(8,8))
plt.pie(rating_counts, labels=rating_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
plt.title("Distribution of Book Ratings")
plt.axis('equal')
plt.tight_layout()
plt.show()

""" **5. Relationship between Price and Rating**
We visualized the relationship between a book’s price and its rating.
Observation: There is no strong correlation between book price and rating. Expensive books do not necessarily have higher ratings, indicating that price is not a guarantee of better quality.


"""

plt.figure(figsize=(10,6))
sns.scatterplot(x="Rating", y="Price (incl. tax)", data=df, hue="Genre", palette="tab10", alpha=0.7)
plt.title("Price vs. Rating of Books")
plt.xlabel("Rating")
plt.ylabel("Price (£)")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')#used to move the legend outside the plot
plt.tight_layout()
plt.show()

"""# **5. Storing data on MongoDB & Streamlit**"""

#!pip install pymongo streamlit

import streamlit as st
import pymongo

client = pymongo.MongoClient("mongodb+srv://youssefelfekywork:peYvupj3jGH9VTK3@dstools1.ju8jwny.mongodb.net/?retryWrites=true&w=majority&appName=DSTools1")
db = client["DSTools1"]

db.books_cleaned.insert_many(df.to_dict('records'))
#db.avg_price_per_genre.insert_many(avg_price_genre.to_dict('records'))
#db.avg_rating_per_genre.insert_many(avg_rating_genre.to_dict('records'))
#db.rating_distribution.insert_many(rating_counts.to_dict('records'))

db.avg_price_genre.insert_many(avg_price_genre.reset_index().to_dict('records'))
db.avg_rating_per_genre.insert_many(avg_rating_genre.reset_index().to_dict('records'))
db.rating_distribution.insert_many(rating_counts.reset_index().to_dict('records'))

import ssl
books = pd.DataFrame(list(db.books_cleaned.find()))
avg_price = pd.DataFrame(list(db.avg_price_genre.find()))
avg_rating = pd.DataFrame(list(db.avg_rating_per_genre.find()))
rating_dist = pd.DataFrame(list(db.rating_distribution.find()))

avg_price

avg_rating

rating_dist

st.title("Book Analysis Dashboard")

st.header("Books Cleaned Data")
st.dataframe(books)

st.header("Average Price per Genre")
st.bar_chart(avg_price.set_index('Genre')['Price (incl. tax)'])

st.header("Average Rating per Genre")
st.bar_chart(avg_rating.set_index('Genre')['Rating'])

st.header("Rating Distribution")
st.bar_chart(rating_dist.set_index('Rating')['count'])